language: go

services:
  - mongodb
env:
  - DB_HOST="127.0.0.1:27017"
go:
  - tip

# Disable installing anything by just running the program `true`
install: true

# Get a list of all non-vendor directories with test files and test them.
# We could just do `go test ./...` but we have some packages that aren't
# intended to compile
script:
  - find . -name "*_test.go" -not -wholename "*vendor*" -exec dirname {} \; | uniq | xargs go test
